=== jizel/deskal/trunk/DesKal/calendar-schemaa.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:element name="calendar">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="labels" type="userTypeTag"/>
                <xsd:element name="event" minOccurs="0" maxOccurs="unbounded" type="userTypeEvent" />
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="eventID">
            <xsd:selector xpath="event"/>
            <xsd:field xpath="@id"/>
        </xsd:unique>
        <xsd:unique name="tag">
            <xsd:selector xpath="labels/tag"/>
            <xsd:field xpath="text"/>
        </xsd:unique>
    </xsd:element>

    <xsd:element name="tag" type="xsd:string"/>

    <xsd:complexType name="userTypeEvent">
        <xsd:sequence>
            <xsd:element name="since" type="xsd:time"/>
            <xsd:element name="duration" type="xsd:duration"/>
            <xsd:element name="date" type="xsd:date"/>
            <xsd:element name="title">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:minLength value="1" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="place" type="xsd:string" minOccurs="0"/>
            <xsd:element name="note" type="xsd:string" minOccurs="0"/>
            <xsd:element name="tags" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element ref="tag" minOccurs="1" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:integer" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="userTypeTag">
            <xsd:sequence>              
                <xsd:element ref="tag" />
            </xsd:sequence>
        </xsd:complexType>


        

</xsd:schema>

=== jizel/deskal/trunk/DesKal/calendar-schema1.11.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : calendar-schema1.11.xml
    Created on : 28. duben 2011, 19:43
    Author     : AdiC
    Description:
        Purpose of the document follows.
-->

<calendar xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='calendar-schemaa.xsd' >
    <labels>
        <tag>blue</tag>
        
    </labels>
    <event id="1">
        <since>12:12:12</since>
        <duration>PT1H</duration>
        <date>2011-04-14</date>
        <title>a</title>
        <place></place>
        <note></note>
        <tags>
            <tag>blue</tag>
        </tags>
    </event>
    <event id="2">
        <since>12:12:12</since>
        <duration>PT1H</duration>
        <date>2011-03-11</date>
        <title>b</title>
        <place></place>
        <note></note>
         <tags>
            <tag>white</tag>
        </tags>
    </event>

</calendar>
