=== jizel/deskal/DesKal/calendar-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/calendar-schema"
    xmlns:tns="http://xml.netbeans.org/schema/calendar-schema"
    elementFormDefault="qualified">
    <xsd:element name="tags">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="tag" type="xsd:string" maxOccurs="unbounded" minOccurs="0" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="calendar">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="event">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="since" type="xsd:time"/>
                            <xsd:element name="to" type="xsd:time"/>
                            <xsd:element name="date" type="xsd:date"/>
                            <xsd:element name="title" type="xsd:string"/>
                            <xsd:element name="place" type="xsd:string"/>
                            <xsd:element name="note" type="xsd:string"/>
                            <xsd:element name="labels" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element ref="tags" minOccurs="0" maxOccurs="unbounded" />
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            
                        </xsd:sequence>
                        <xsd:attribute name="id" type="xsd:integer" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>    
</xsd:schema>

=== jizel/deskal/trunk/DesKal/calendar1.1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : calendar1.1.xml
    Created on : 28. duben 2011, 19:37
    Author     : AdiC
    Description:
        Purpose of the document follows.
-->

<xs:calendar  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:xs='http://xml.netbeans.org/schema/calendar-schema'
   xsi:schemaLocation='http://xml.netbeans.org/schema/calendar-schema calendar-schema.xsd'>
    <xs:event id="">
        <xs:since></xs:since>
        <xs:duration></xs:duration>
        <xs:date></xs:date>
        <xs:title></xs:title>
        <xs:place></xs:place>
        <xs:note></xs:note>
        <xs:labels>
            <xs:tag></xs:tag>
            <xs:tag></xs:tag>
            <xs:tag></xs:tag>
        </xs:labels>
    </xs:event>
    <xs:event id="">
        <xs:since></xs:since>
        <xs:duration></xs:duration>
        <xs:date></xs:date>
        <xs:title></xs:title>
        <xs:place></xs:place>
        <xs:note></xs:note>
        <xs:labels>
            <xs:tag></xs:tag>
            <xs:tag></xs:tag>
            <xs:tag></xs:tag>
        </xs:labels>
    </xs:event>
    <xs:event id="">
        <xs:since></xs:since>
        <xs:duration></xs:duration>
        <xs:date></xs:date>
        <xs:title></xs:title>
        <xs:place></xs:place>
        <xs:note></xs:note>
        <xs:labels>
            <xs:tag></xs:tag>
            <xs:tag></xs:tag>
            <xs:tag></xs:tag>
        </xs:labels>
    </xs:event>

</xs:calendar>

=== jizel/deskal/trunk/DesKal/calendar.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : calendar.xml
    Created on : 27. duben 2011, 16:13
    Author     : AdiC
    Description:
        Purpose of the document follows.
-->

<xs:calendar  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:xs='http://xml.netbeans.org/schema/calendar-schema'
   xsi:schemaLocation='http://xml.netbeans.org/schema/calendar-schema calendar-schema.xsd'>
    <xs:event id="">
        <xs:since></xs:since>
        <xs:to></xs:to>
        <xs:date></xs:date>
        <xs:title></xs:title>
        <xs:place></xs:place>
        <xs:note></xs:note>
    </xs:event>

</xs:calendar>

=== jizel/deskal/DesKal/calendar.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : calendar.xml
    Created on : 27. duben 2011, 16:13
    Author     : AdiC
    Description:
        Purpose of the document follows.
-->

<xs:calendar  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:xs='http://xml.netbeans.org/schema/calendar-schema'
   xsi:schemaLocation='http://xml.netbeans.org/schema/calendar-schema calendar-schema.xsd'>
    <xs:event id="1">
        <xs:since>12:00:00</xs:since>
        <xs:duration>PT1H</xs:duration>
        <xs:date>2011-04-30</xs:date>
        <xs:title>Title1 - noPlace noNote noLabels</xs:title>
    </xs:event>
    <xs:event id="2">
        <xs:since>13:00:00</xs:since>
        <xs:duration>PT1H</xs:duration>
        <xs:date>2011-05-31</xs:date>
        <xs:title>Title2 - noNote noLabels</xs:title>
        <xs:place>Brno</xs:place>
    </xs:event>
    <xs:event id="3">
        <xs:since>12:00:00</xs:since>
        <xs:duration>PT1H</xs:duration>
        <xs:date>2011-04-30</xs:date>
        <xs:title>Title13 - noPlace noNote</xs:title>
        <xs:labels>
            <xs:tag>work</xs:tag>
        </xs:labels>
    </xs:event>
    <xs:event id="4">
        <xs:since>12:00:00</xs:since>
        <xs:duration>PT1H</xs:duration>
        <xs:date>2011-04-30</xs:date>
        <xs:title>Title4</xs:title>
        <xs:place>Prague</xs:place>
        <xs:note>new note</xs:note>     
        <xs:labels>
            <xs:tag>Work</xs:tag>
            <xs:tag>Important</xs:tag>
        </xs:labels>
    </xs:event>
 
</xs:calendar>

=== jizel/deskal/baseX/calendar.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : calendar-schema1.11.xml
    Created on : 28. duben 2011, 19:43
    Author     : AdiC
    Description:
        Purpose of the document follows.
-->

<calendar xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='calendar-schema.xsd' >
    <labels>
        <label name="blue"/>
        <label name="white"/>
    </labels>
    <event id="1">
        <duration>PT1H5M6S</duration>
        <date>2011-04-14T12:12:12</date>
        <title>a</title>
        <place>Brno</place>
        <note>Nix</note>
        <tags>
            <tag tagref="blue"/>
            <tag tagref="white"/>
        </tags>
    </event>
   <event id="2">
        <duration>PT1H</duration>
        <date>2011-03-11T12:12:12</date>
        <title>b</title>
        <place>tu</place>
        <note>nout</note>
         <tags>
            <tag tagref="white"/>
        </tags>
    </event>
    <event id="3">
        <duration>PT1H</duration>
        <date>2011-03-11T12:12:12</date>
        <title>C</title>
        <place></place>
        <note></note>
    </event>

</calendar>

=== jizel/deskal/trunk/DesKal/calendar-schema.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : calendar-schema1.11.xml
    Created on : 28. duben 2011, 19:43
    Author     : AdiC
    Description:
        Purpose of the document follows.
-->

<calendar xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='calendar-schema.xsd' >
    <labels>
        <label name="blue"/>
        <label name="white"/>
    </labels>
    <event id="1">
        <since>12:12:12</since>
        <duration>PT1H5M6S</duration>
        <date>2011-04-14</date>
        <title>a</title>
        <place>Brno</place>
        <note>Nix</note>
        <tags>
            <tag tagref="blue"/>
            <tag tagref="white"/>
        </tags>
    </event>
   <event id="2">
        <since>12:12:12</since>
        <duration>PT1H</duration>
        <date>2011-03-11</date>
        <title>b</title>
        <place></place>
        <note></note>
         <tags>
            <tag tagref="white"/>
        </tags>
    </event>
    <event id="3">
        <since>12:12:12</since>
        <duration>PT1H</duration>
        <date>2011-03-11</date>
        <title>C</title>
        <place></place>
        <note></note>
    </event>

</calendar>
